import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Profile from "@/components/custom/profile-card/profile-card";
import Navbar from "@/components/custom/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black min-h-screen`}
      >
        <div className="flex flex-col mb-25 xl:mb-0 xl:flex-row justify-center xl:justify-start xl:h-screen">
          <Profile />
          <div className="relative w-full xl:ml-20 2xl:mx-20">
            {children}
            <div className="fixed xl:absolute bottom-10 2xl:bottom-20 w-full flex justify-center">
              <Navbar />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
